# lighten
a = lighten(#f00,30%)
a = lighten(#f00,30%,relative)
a = lighten(#f88,30%,autoInverse)
a = lighten(#f88,30%,relative autoInverse)
a = lighten(Actions.Red,10%,lazy)

# darken
a = darken(#f00,30%)
a = darken(#f00,30%,relative)
a = darken(#a00,30%,autoInverse)
a = darken(#a00,30%,relative autoInverse)
a = darken(Actions.Red,10%,lazy)

# saturate
a = saturate(#966,30%)
a = saturate(#966,30%,relative)
a = saturate(#d33,30%,autoInverse)
a = saturate(#d33,30%,relative autoInverse)
a = saturate(Actions.Red,10%,lazy)

# desaturate
a = desaturate(#d33,30%)
a = desaturate(#d33,30%,relative)
a = desaturate(#966,30%,autoInverse)
a = desaturate(#966,30%,relative autoInverse)
a = desaturate(Actions.Red,10%,lazy)

# fadein
a = fadein(#f004,30%)
a = fadein(#f004,30%,relative)
a = fadein(#f00a,30%,autoInverse)
a = fadein(#f00a,30%,relative autoInverse)
a = fadein(Actions.Red,50%,lazy)

# fadeout
a = fadeout(#f00a,30%)
a = fadeout(#f00a,30%,relative)
a = fadeout(#f004,30%,autoInverse)
a = fadeout(#f004,30%,relative autoInverse)
a = fadeout(Actions.Red,50%,lazy)

# fade
a = fade(#f00,50%)
a = fade(Actions.Red,50%,lazy)

# spin
a = spin(#f00,30)
a = spin(Actions.Red,30,lazy)

# changeHue
a = changeHue(#f00,180)
a = changeHue(Actions.Red,180,lazy)

# changeSaturation
a = changeSaturation(#f00,50%)
a = changeSaturation(Actions.Red,50%,lazy)

# changeLightness
a = changeLightness(#f00,80%)
a = changeLightness(Actions.Red,80%,lazy)

# changeAlpha
a = changeAlpha(#f00,50%)
a = changeAlpha(Actions.Red,50%,lazy)

# mix
a = mix(#f00,#0f0,40%)
a = mix(#f00,#0f0,40%,lrgb)
a = mix(#f00,#0f0,40%,oklab)
a = mix(#0f0,Actions.Red,50%,lazy)

# tint
a = tint(#f00,40%)
a = tint(#f00,40%,lrgb)
a = tint(#f00,40%,oklab)
a = tint(Actions.Red,50%,lazy)

# shade
a = shade(#f00,20%)
a = shade(#f00,20%,lrgb)
a = shade(#f00,20%,oklab)
a = shade(Actions.Red,20%,lazy)
